################################################################################
#
# Makefile grand central
#
################################################################################

all:
	$(MAKE) -C NICAM
#	$(MAKE) -C DYNAMICO
#	$(MAKE) -C ICON

clean:
	$(MAKE) -C NICAM    clean
#	$(MAKE) -C DYNAMICO clean
#	$(MAKE) -C ICON     clean

data:
	$(MAKE) -C NICAM    data
#	$(MAKE) -C DYNAMICO data
#	$(MAKE) -C ICON     data

run:
	$(MAKE) -C NICAM    run
#	$(MAKE) -C DYNAMICO run
#	$(MAKE) -C ICON     run
