################################################################################
#
# Makefile grand central
#
################################################################################

all:
	$(MAKE) -C NICAM/src
#	$(MAKE) -C DYNAMICO/src
#	$(MAKE) -C ICON/src

clean:
	$(MAKE) -C NICAM/src    clean
#	$(MAKE) -C DYNAMICO/src clean
#	$(MAKE) -C ICON/src     clean
